package org.omg.hw.multiLayerSubnetwork;

/**
 *	Generated from IDL interface "MultiLayerSubnetworkMgr_I"
 *	@author JacORB IDL compiler V 2.2.3, 10-Dec-2005
 */


public interface MultiLayerSubnetworkMgr_IOperations
	extends org.omg.hw.common.Common_IOperations
{
	/* constants */
	/* operations  */
	void getAllManagedElements(org.omg.hw.globaldefs.NameAndStringValue_T[] subnetName, int how_many, org.omg.hw.managedElement.ManagedElementList_THolder meList, org.omg.hw.managedElement.ManagedElementIterator_IHolder meIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllManagedElementNames(org.omg.hw.globaldefs.NameAndStringValue_T[] subnetName, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getMultiLayerSubnetwork(org.omg.hw.globaldefs.NameAndStringValue_T[] subnetName, org.omg.hw.multiLayerSubnetwork.MultiLayerSubnetwork_THolder subnetwork) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllTopologicalLinks(org.omg.hw.globaldefs.NameAndStringValue_T[] subnetName, int how_many, org.omg.hw.topologicalLink.TopologicalLinkList_THolder topoList, org.omg.hw.topologicalLink.TopologicalLinkIterator_IHolder topoIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllTopologicalLinkNames(org.omg.hw.globaldefs.NameAndStringValue_T[] subnetName, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllInternalTopologicalLinks(org.omg.hw.globaldefs.NameAndStringValue_T[] meName, int how_many, org.omg.hw.topologicalLink.TopologicalLinkList_THolder topoList, org.omg.hw.topologicalLink.TopologicalLinkIterator_IHolder topoIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllInternalTopologicalLinkNames(org.omg.hw.globaldefs.NameAndStringValue_T[] meName, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getTopologicalLink(org.omg.hw.globaldefs.NameAndStringValue_T[] topoLinkName, org.omg.hw.topologicalLink.TopologicalLink_THolder topoLink) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllEdgePoints(org.omg.hw.globaldefs.NameAndStringValue_T[] subnetName, short[] tpLayerRateList, short[] connectionLayerRateList, int how_many, org.omg.hw.terminationPoint.TerminationPointList_THolder tpList, org.omg.hw.terminationPoint.TerminationPointIterator_IHolder tpIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllEdgePointNames(org.omg.hw.globaldefs.NameAndStringValue_T[] subnetName, short[] layerRateList, short[] connectionLayerRateList, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAssociatedTP(org.omg.hw.globaldefs.NameAndStringValue_T[] tpName, org.omg.hw.terminationPoint.TerminationPointList_THolder tpList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getTPGroupingRelationships(org.omg.hw.globaldefs.NameAndStringValue_T[] tpName, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnections(org.omg.hw.globaldefs.NameAndStringValue_T[] subnetName, short[] connectionRateList, int how_many, org.omg.hw.subnetworkConnection.SubnetworkConnectionList_THolder sncList, org.omg.hw.subnetworkConnection.SNCIterator_IHolder sncIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnectionNames(org.omg.hw.globaldefs.NameAndStringValue_T[] subnetName, short[] connectionRateList, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnectionsWithTP(org.omg.hw.globaldefs.NameAndStringValue_T[] tpName, short[] connectionRateList, int how_many, org.omg.hw.subnetworkConnection.SubnetworkConnectionList_THolder sncList, org.omg.hw.subnetworkConnection.SNCIterator_IHolder sncIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnectionNamesWithTP(org.omg.hw.globaldefs.NameAndStringValue_T[] tpName, short[] connectionRateList, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getRoute(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, boolean includeHigherOrderCCs, org.omg.hw.subnetworkConnection.Route_THolder route) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getRoutes(org.omg.hw.globaldefs.NameAndStringValue_T[][] sncNameList, boolean includeHigherOrderCCs, org.omg.hw.subnetworkConnection.RouteInfoList_THolder routeInfoList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getRouteAndTopologicalLinksBySNCs(org.omg.hw.globaldefs.NameAndStringValue_T[][] sncNameList, int how_many, org.omg.hw.multiLayerSubnetwork.RouteAndTopologicalLinkList_THolder routeAndTlList, org.omg.hw.multiLayerSubnetwork.RouteAndTopologicalLinkIterator_IHolder routeAndTlIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getSNC(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, org.omg.hw.subnetworkConnection.SubnetworkConnection_THolder snc) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getSNCs(org.omg.hw.globaldefs.NameAndStringValue_T[][] sncNameList, org.omg.hw.subnetworkConnection.SubnetworkConnectionList_THolder sncList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getSNCsByEndObjectName(org.omg.hw.globaldefs.NameAndStringValue_T[] aEndObjectName, org.omg.hw.globaldefs.NameAndStringValue_T[] zEndObjectName, short[] connectionRateList, org.omg.hw.subnetworkConnection.SubnetworkConnectionList_THolder sncList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getSNCsByNativeEmsName(java.lang.String nativeEmsName, int how_many, org.omg.hw.subnetworkConnection.SubnetworkConnectionList_THolder sncList, org.omg.hw.subnetworkConnection.SNCIterator_IHolder sncIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getSNCsByUserLabel(java.lang.String userLabel, org.omg.hw.subnetworkConnection.SubnetworkConnectionList_THolder sncList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createSNC(org.omg.hw.subnetworkConnection.SNCCreateData_T createData, org.omg.hw.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.omg.hw.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.omg.hw.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void modifySNC(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, java.lang.String routeId, org.omg.hw.subnetworkConnection.SNCModifyData_T SNCModifyData, org.omg.hw.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.omg.hw.subnetworkConnection.ProtectionEffort_T tolerableImpactEffort, org.omg.hw.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.subnetworkConnection.SubnetworkConnection_THolder newSNC, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void activateSNC(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, org.omg.hw.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.omg.hw.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createAndActivateSNC(org.omg.hw.subnetworkConnection.SNCCreateData_T createData, org.omg.hw.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.omg.hw.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deactivateSNC(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, org.omg.hw.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.omg.hw.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deleteSNC(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, org.omg.hw.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deactivateAndDeleteSNC(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, org.omg.hw.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.omg.hw.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void checkValidSNC(org.omg.hw.subnetworkConnection.SNCCreateData_T createData, org.omg.hw.subnetworkConnection.TPData_T[] tpsToModify, boolean considerResources, org.omg.CORBA.BooleanHolder valid) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllTPPools(org.omg.hw.globaldefs.NameAndStringValue_T[] subnetworkName, int how_many, org.omg.hw.terminationPoint.TerminationPointList_THolder tpList, org.omg.hw.terminationPoint.TerminationPointIterator_IHolder tpIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllTPPoolNames(org.omg.hw.globaldefs.NameAndStringValue_T[] subnetworkName, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getRouteAndTopologicalLinks(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, org.omg.hw.subnetworkConnection.Route_THolder route, org.omg.hw.topologicalLink.TopologicalLinkList_THolder topologicalLinkList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void setConjunctionSNC(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName1, org.omg.hw.globaldefs.NameAndStringValue_T[] sncName2, boolean operate) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void swapSNC(org.omg.hw.globaldefs.NameAndStringValue_T[] nameOfSNCtoBeDeactivated, org.omg.hw.globaldefs.NameAndStringValue_T[] nameOfSNCtoBeActivated, org.omg.hw.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.omg.hw.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.subnetworkConnection.SNCState_THolder stateOfActivatedSNC, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getWaveLengthStatusByEndObject(org.omg.hw.globaldefs.NameAndStringValue_T[] aEndName, org.omg.hw.globaldefs.NameAndStringValue_T[][] inclusionNameList, org.omg.hw.globaldefs.NameAndStringValue_T[][] exclusionNameList, org.omg.hw.globaldefs.NameAndStringValue_T[] zEndName, org.omg.hw.globaldefs.ConnectionDirection_T direction, org.omg.hw.subnetworkConnection.WaveLengthStatusList_THolder waveLengthStatusList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getOrginalRoute(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, boolean includeHigherOrderCCs, org.omg.hw.subnetworkConnection.Route_THolder route) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getPresetRoute(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, int presetRouteID, org.omg.hw.subnetworkConnection.PresetRoute_THolder route) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getOrginalPresetRoute(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, int presetRouteID, org.omg.hw.subnetworkConnection.PresetRoute_THolder route) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deletePresetRoute(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, int presetRouteID) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createPresetRoute(org.omg.hw.subnetworkConnection.CreatePresetRouteData_T createData, org.omg.hw.subnetworkConnection.PresetRoute_THolder route) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getSharedRoute(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, int sharedRouteID, org.omg.hw.subnetworkConnection.SharedRoute_THolder route) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deleteSharedRoute(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, int sharedRouteID) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createSharedRoute(org.omg.hw.subnetworkConnection.CreateSharedRouteData_T createData, org.omg.hw.subnetworkConnection.SharedRoute_THolder route) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void switchRoute(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName, java.lang.String routeId, org.omg.hw.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.omg.hw.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.globaldefs.NVSList_THolder additionalInfo, org.omg.hw.subnetworkConnection.SNCState_THolder sncState, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getSNCNamesByRouteModificationTime(java.lang.String utcBeginTime, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllSNCNamesWithHigherOrderSNC(org.omg.hw.globaldefs.NameAndStringValue_T[] name, short[] connectivityRateList, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllMicrowaveLinksReport(java.lang.String destination, java.lang.String userName, java.lang.String password, org.omg.hw.notifications.NameAndAnyValue_T[] filter) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void setConjunctionSNCEx(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName1, org.omg.hw.globaldefs.NameAndStringValue_T[] sncName2, org.omg.hw.globaldefs.NameAndStringValue_T[] additionalInfo, boolean operate) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllConjunctionSNCs(int how_many, org.omg.hw.multiLayerSubnetwork.HW_ConjunctionSNCList_THolder conjunctionSNCList, org.omg.hw.multiLayerSubnetwork.HW_ConjunctionSNCIterator_IHolder conjunctionSNCIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getConjunctionSNC(org.omg.hw.globaldefs.NameAndStringValue_T[] sncName1, org.omg.hw.globaldefs.NVSList_THolder sncName2, org.omg.hw.globaldefs.NVSList_THolder additionalInfo) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getServerConnections(org.omg.hw.globaldefs.NameAndStringValue_T[] clientName, org.omg.hw.subnetworkConnection.ServerTrailList_THolder serverInfoList) throws org.omg.hw.globaldefs.ProcessingFailureException;
}
