package org.omg.hw.flowDomain_cmcc;

/**
 *	Generated from IDL interface "FlowDomainMgr_cmcc_I"
 *	@author JacORB IDL compiler V 2.2.3, 10-Dec-2005
 */


public interface FlowDomainMgr_cmcc_IOperations
	extends org.omg.hw.common.Common_IOperations
{
	/* constants */
	/* operations  */
	void getAllFlowDomains(int how_many, org.omg.hw.flowDomain_cmcc.FDList_THolder flowDomains, org.omg.hw.flowDomain_cmcc.FDIterator_IHolder fdIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFlowDomainsByUserLabel(java.lang.String userLabel, org.omg.hw.flowDomain_cmcc.FDList_THolder flowDomains) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFlowDomain(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, org.omg.hw.flowDomain_cmcc.FlowDomain_THolder flowDomain) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAssociatingFD(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdName, org.omg.hw.flowDomain_cmcc.FlowDomain_THolder flowDomain) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getTransmissionParams(org.omg.hw.globaldefs.NameAndStringValue_T[] name, java.lang.String[] filter, org.omg.hw.transmissionParameters.LayeredParameterList_THolder transmissionParams) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createFlowDomain(org.omg.hw.flowDomain_cmcc.FDCreateData_T createData, org.omg.hw.globaldefs.NamingAttributesList_THolder assignedCPTPs, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.flowDomain_cmcc.FlowDomain_THolder theFD, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deleteFlowDomain(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void modifyFlowDomain(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, org.omg.hw.flowDomain_cmcc.FDModifyData_T fdModifyData, org.omg.hw.flowDomain_cmcc.FlowDomain_THolder modifiedFD, org.omg.CORBA.StringHolder failedAttributes, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void associateMFDsWithFlowDomain(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, org.omg.hw.globaldefs.NameAndStringValue_T[][] mfdNames, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deAssociateMFDsFromFlowDomain(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, org.omg.hw.globaldefs.NameAndStringValue_T[][] mfdNames, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void associateCPTPsWithFlowDomain(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, org.omg.hw.globaldefs.NameAndStringValue_T[][] cptpNames, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deAssociateCPTPsFromFlowDomain(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, org.omg.hw.globaldefs.NameAndStringValue_T[][] tpNames, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllAssociatedMFDs(org.omg.hw.globaldefs.NameAndStringValue_T[] tmdOrFdName, int how_many, org.omg.hw.flowDomain_cmcc.MFDList_THolder mfds, org.omg.hw.flowDomain_cmcc.MFDIterator_IHolder mfdIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllSupportedMFDs(org.omg.hw.globaldefs.NameAndStringValue_T[] holderName, int how_many, org.omg.hw.flowDomain_cmcc.MFDList_THolder mfds, org.omg.hw.flowDomain_cmcc.MFDIterator_IHolder mfdIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getMFD(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdName, org.omg.hw.flowDomain_cmcc.MatrixFlowDomain_THolder mfd) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAssigningMFD(org.omg.hw.globaldefs.NameAndStringValue_T[] cptpName, org.omg.hw.flowDomain_cmcc.MatrixFlowDomain_THolder mfd) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createMFD(org.omg.hw.flowDomain_cmcc.MFDCreateData_T createData, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.flowDomain_cmcc.MatrixFlowDomain_THolder theMFD, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deleteMFD(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdName, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void modifyMFD(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdName, org.omg.hw.flowDomain_cmcc.MFDModifyData_T mfdModifyData, org.omg.hw.flowDomain_cmcc.MatrixFlowDomain_THolder newMFD, org.omg.CORBA.StringHolder failedAttributes, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void assignCPTPsToMFD(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdName, org.omg.hw.globaldefs.NameAndStringValue_T[][] tpNames, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void unassignCPTPsFromMFD(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdName, org.omg.hw.globaldefs.NameAndStringValue_T[][] tpNames, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createFTP(org.omg.hw.flowDomain_cmcc.FTPCreateData_T createData, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.terminationPoint.TerminationPoint_THolder theFTP, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deleteFTP(org.omg.hw.globaldefs.NameAndStringValue_T[] ftpName, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllCPTPs(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, org.omg.hw.flowDomain_cmcc.CPTP_Role_T cptpRole, int how_many, org.omg.hw.terminationPoint.TerminationPointList_THolder cptpList, org.omg.hw.terminationPoint.TerminationPointIterator_IHolder cptpIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllAssignedCPTPs(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdName, int how_many, org.omg.hw.terminationPoint.TerminationPointList_THolder cptpList, org.omg.hw.terminationPoint.TerminationPointIterator_IHolder cptpIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllAssignableCPTPs(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdName, int how_many, org.omg.hw.terminationPoint.TerminationPointList_THolder cptpList, org.omg.hw.terminationPoint.TerminationPointIterator_IHolder cptpIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllFDFrs(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, int how_many, short[] connectivityRateList, org.omg.hw.flowDomainFragment_cmcc.FDFrList_THolder fdfrList, org.omg.hw.flowDomainFragment_cmcc.FDFrIterator_IHolder fdfrIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFDFrsWithTP(org.omg.hw.globaldefs.NameAndStringValue_T[] cptpName, int how_many, org.omg.hw.flowDomainFragment_cmcc.FDFrList_THolder fdfrList, org.omg.hw.flowDomainFragment_cmcc.FDFrIterator_IHolder fdfrIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFDFrsByUserLabel(java.lang.String userLabel, org.omg.hw.flowDomainFragment_cmcc.FDFrList_THolder fdfrs) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.flowDomainFragment_cmcc.FlowDomainFragment_THolder fdfr) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createAndActivateFDFr(org.omg.hw.flowDomainFragment_cmcc.FDFrCreateData_T createData, org.omg.hw.flowDomain_cmcc.ConnectivityRequirement_T connectivityRequirement, org.omg.hw.globaldefs.NameAndStringValue_T[][] aEnd, org.omg.hw.globaldefs.NameAndStringValue_T[][] zEnd, org.omg.hw.globaldefs.NamingAttributesList_THolder internalTPs, org.omg.hw.flowDomainFragment_cmcc.MatrixFlowDomainFragmentList_THolder mfdfrs, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.flowDomainFragment_cmcc.FlowDomainFragment_THolder theFDFr, org.omg.hw.globaldefs.NamingAttributesList_THolder notConnectableCPTPList, org.omg.hw.globaldefs.NamingAttributesList_THolder parameterProblemsTPList, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deactivateAndDeleteFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.flowDomainFragment_cmcc.FlowDomainFragment_THolder theFDFr, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void modifyFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.flowDomainFragment_cmcc.FDFrModifyData_T fdfrModifyData, org.omg.hw.flowDomain_cmcc.ConnectivityRequirement_T connectivityRequirement, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.globaldefs.NamingAttributesList_THolder failedTPList, org.omg.hw.globaldefs.NamingAttributesList_THolder parameterProblemsTPList, org.omg.hw.flowDomainFragment_cmcc.FlowDomainFragment_THolder newFDFr, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllTopologicalLinksOfFD(org.omg.hw.globaldefs.NameAndStringValue_T[] flowDomainName, int how_many, org.omg.hw.topologicalLink.TopologicalLinkList_THolder topoList, org.omg.hw.topologicalLink.TopologicalLinkIterator_IHolder topoIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFDFrRoute(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.flowDomainFragment_cmcc.FDFrRoute_THolder route) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createFDFr(org.omg.hw.flowDomainFragment_cmcc.FDFrCreateData_T createData, org.omg.hw.flowDomain_cmcc.ConnectivityRequirement_T connectivityRequirement, org.omg.hw.subnetworkConnection.TPData_T[] aEnd, org.omg.hw.subnetworkConnection.TPData_T[] zEnd, org.omg.hw.globaldefs.NamingAttributesList_THolder internalTPs, org.omg.hw.flowDomainFragment_cmcc.MatrixFlowDomainFragmentList_THolder mfdfrs, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.flowDomainFragment_cmcc.FlowDomainFragment_THolder theFDFr, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void activateFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.flowDomainFragment_cmcc.FlowDomainFragment_THolder fdfr) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deactivateFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.flowDomainFragment_cmcc.FlowDomainFragment_THolder fdfr) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deleteFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName) throws org.omg.hw.globaldefs.ProcessingFailureException;
}
