package org.omg.hw.HW_vpnManager;

/**
 *	Generated from IDL interface "HW_VPNMgr_I"
 *	@author JacORB IDL compiler V 2.2.3, 10-Dec-2005
 */


public interface HW_VPNMgr_IOperations
	extends org.omg.hw.common.Common_IOperations
{
	/* constants */
	/* operations  */
	void createMFDFr(org.omg.hw.HW_vpnManager.MatrixFlowDomainFragment_T createData, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.HW_vpnManager.MatrixFlowDomainFragment_THolder theMFDFr, org.omg.hw.globaldefs.NamingAttributesList_THolder notConnectableCPTPList, org.omg.hw.globaldefs.NamingAttributesList_THolder parameterProblemsTPList, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void modifyMFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdfrName, org.omg.hw.HW_vpnManager.MFDFrModifyData_T modifyData, org.omg.hw.HW_vpnManager.MatrixFlowDomainFragment_THolder theMFDFr, org.omg.hw.globaldefs.NamingAttributesList_THolder notConnectableCPTPList, org.omg.hw.globaldefs.NamingAttributesList_THolder parameterProblemsTPList, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deleteMFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdfrName) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void activateMFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdfrName, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.HW_vpnManager.MatrixFlowDomainFragment_THolder theMFDFr, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deactivateMFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdfrName, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.HW_vpnManager.MatrixFlowDomainFragment_THolder theMFDFr, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllMFDFrs(org.omg.hw.globaldefs.NameAndStringValue_T[] meName, short[] connectionRateList, int how_many, org.omg.hw.HW_vpnManager.MatrixFlowDomainFragmentList_THolder mfdfrList, org.omg.hw.HW_vpnManager.MFDFrIterator_IHolder mfdfrIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllMFDFrNames(org.omg.hw.globaldefs.NameAndStringValue_T[] meName, short[] connectionRateList, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getMFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] mfdfrName, org.omg.hw.HW_vpnManager.MatrixFlowDomainFragment_THolder theMFDFr) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllTrafficTrunksWithME(org.omg.hw.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, org.omg.hw.HW_vpnManager.TrafficTrunkList_THolder trafficTrunkList, org.omg.hw.HW_vpnManager.TrafficTrunkIterator_IHolder trafficTrunkIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllTrafficTrunkNamesWithME(org.omg.hw.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createTrafficTrunk(org.omg.hw.HW_vpnManager.TrafficTrunkCreateData_T createData, org.omg.hw.HW_vpnManager.TrafficTrunk_THolder theTrafficTrunk, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deleteTrafficTrunk(org.omg.hw.globaldefs.NameAndStringValue_T[] trafficTrunkName) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void activateTrafficTrunk(org.omg.hw.globaldefs.NameAndStringValue_T[] trafficTrunkName, org.omg.hw.HW_vpnManager.TrafficTrunk_THolder theTrafficTrunk, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deactivateTrafficTrunk(org.omg.hw.globaldefs.NameAndStringValue_T[] trafficTrunkName, org.omg.hw.HW_vpnManager.TrafficTrunk_THolder theTrafficTrunk, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getTrafficTrunk(org.omg.hw.globaldefs.NameAndStringValue_T[] trafficTrunkName, org.omg.hw.HW_vpnManager.TrafficTrunk_THolder trafficTrunk) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void modifyTrafficTrunk(org.omg.hw.globaldefs.NameAndStringValue_T[] trafficTrunkName, org.omg.hw.HW_vpnManager.TrafficTrunkModifyData_T modifyData, org.omg.hw.HW_vpnManager.TrafficTrunk_THolder newTrafficTrunk, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllIPCrossConnections(org.omg.hw.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, org.omg.hw.HW_vpnManager.IPCrossConnectionList_THolder ipCCList, org.omg.hw.HW_vpnManager.IPCrossConnectionIterator_IHolder ipCCIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllIPCrossConnectionNames(org.omg.hw.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createIPCrossConnections(org.omg.hw.HW_vpnManager.IPCrossConnection_T[] ipCCList, org.omg.hw.HW_vpnManager.IPCrossConnectionList_THolder successedIPCCList, org.omg.hw.HW_vpnManager.IPCrossConnectionList_THolder failedIPCCList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deleteIPCrossConnections(org.omg.hw.globaldefs.NameAndStringValue_T[][] ipCCNameList, org.omg.hw.globaldefs.NamingAttributesList_THolder successedIPCCNameList, org.omg.hw.globaldefs.NamingAttributesList_THolder failedIPCCNameList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getIPCrossConnection(org.omg.hw.globaldefs.NameAndStringValue_T[] ipCCName, org.omg.hw.HW_vpnManager.IPCrossConnection_THolder ipCC) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void modifyIPCrossConnection(org.omg.hw.globaldefs.NameAndStringValue_T[] ipCCName, org.omg.hw.transmissionParameters.LayeredParameters_T transmissionParams, org.omg.hw.HW_vpnManager.IPCrossConnection_THolder newIPCC, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void activateIPCrossConnections(org.omg.hw.globaldefs.NameAndStringValue_T[][] ipCCNameList, org.omg.hw.globaldefs.NamingAttributesList_THolder successedIPCCNameList, org.omg.hw.globaldefs.NamingAttributesList_THolder failedIPCCNameList, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deactivateIPCrossConnections(org.omg.hw.globaldefs.NameAndStringValue_T[][] ipCCNameList, org.omg.hw.globaldefs.NamingAttributesList_THolder successedIPCCNameList, org.omg.hw.globaldefs.NamingAttributesList_THolder failedIPCCNameList, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void createFDFr(org.omg.hw.HW_vpnManager.FDFrCreateData_T createData, org.omg.hw.flowDomain.ConnectivityRequirement_T connectivityRequirement, org.omg.hw.subnetworkConnection.TPDataList_THolder endTPs, org.omg.hw.subnetworkConnection.TPDataList_THolder internalTPs, org.omg.hw.HW_vpnManager.MatrixFlowDomainFragmentList_THolder mfdfrs, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.HW_vpnManager.FlowDomainFragment_THolder theFDFr, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void modifyFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.HW_vpnManager.FDFrModifyData_T fdfrModifyData, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.hw.subnetworkConnection.GradesOfImpact_T tolerableImpact, org.omg.hw.HW_vpnManager.FlowDomainFragment_THolder newFDFr, org.omg.CORBA.StringHolder errorReason) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deleteFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.subnetworkConnection.TPDataList_THolder tpsToModify) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void activateFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.HW_vpnManager.FlowDomainFragment_THolder fdfr) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void deactivateFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.HW_vpnManager.FlowDomainFragment_THolder fdfr) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getTrafficTrunkRoute(org.omg.hw.globaldefs.NameAndStringValue_T[] trafficTrunkName, org.omg.hw.HW_vpnManager.IPCrossConnectionList_THolder route) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllFDFrs(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, int how_many, short[] connectionRateList, org.omg.hw.HW_vpnManager.FlowDomainFragmentList_THolder fdfrList, org.omg.hw.HW_vpnManager.FDFrIterator_IHolder fdfrIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllFDFrNames(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, int how_many, short[] connectionRateList, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFDFr(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.HW_vpnManager.FlowDomainFragment_THolder theFDFr) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFDFrRoute(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, boolean includeHigherOrderCCs, org.omg.hw.HW_vpnManager.FDFrRoute_THolder route) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFDFrServerTrail(org.omg.hw.globaldefs.NameAndStringValue_T[] fdfrName, org.omg.hw.globaldefs.NamingAttributesList_THolder serverNameList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllTrafficTrunks(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, short[] connectionRateList, int how_many, org.omg.hw.HW_vpnManager.TrafficTrunkList_THolder trafficTrunkList, org.omg.hw.HW_vpnManager.TrafficTrunkIterator_IHolder trafficTrunkIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getAllTrafficTrunkNames(org.omg.hw.globaldefs.NameAndStringValue_T[] fdName, short[] connectionRateList, int how_many, org.omg.hw.globaldefs.NamingAttributesList_THolder nameList, org.omg.hw.globaldefs.NamingAttributesIterator_IHolder nameIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getIPRoutes(org.omg.hw.globaldefs.NameAndStringValue_T[] trafficTrunkName, org.omg.hw.HW_vpnManager.IPCrossConnectionList_THolder routes) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getTrafficTrunksByNativeEmsName(java.lang.String nativeEmsName, org.omg.hw.HW_vpnManager.TrafficTrunkList_THolder trafficTrunkList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getTrafficTrunksByUserLabel(java.lang.String userLabel, org.omg.hw.HW_vpnManager.TrafficTrunkList_THolder trafficTrunkList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getTrafficTrunksWithTP(org.omg.hw.globaldefs.NameAndStringValue_T[] tpName, int how_many, org.omg.hw.HW_vpnManager.TrafficTrunkList_THolder trafficTrunkList, org.omg.hw.HW_vpnManager.TrafficTrunkIterator_IHolder trafficTrunkIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFDFrsByUserLabel(java.lang.String userLabel, org.omg.hw.HW_vpnManager.FlowDomainFragmentList_THolder fdfrList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFDFrsWithME(org.omg.hw.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, org.omg.hw.HW_vpnManager.FlowDomainFragmentList_THolder fdfrList, org.omg.hw.HW_vpnManager.FDFrIterator_IHolder fdfrIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFDFrsWithTP(org.omg.hw.globaldefs.NameAndStringValue_T[] cptpName, int how_many, org.omg.hw.HW_vpnManager.FlowDomainFragmentList_THolder fdfrList, org.omg.hw.HW_vpnManager.FDFrIterator_IHolder fdfrIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getSelfLearningMACAddressTable(org.omg.hw.globaldefs.NameAndStringValue_T[][] nameList, int how_many, org.omg.hw.HW_vpnManager.SelfLearningMACAddressTableList_THolder tableList, org.omg.hw.HW_vpnManager.SelfLearningMACAddressTableIterator_IHolder tableIt) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getIPRoutesByTrafficTrunks(org.omg.hw.globaldefs.NameAndStringValue_T[][] trafficTrunkNameList, org.omg.hw.HW_vpnManager.IPRouteInfoList_THolder routeInfoList) throws org.omg.hw.globaldefs.ProcessingFailureException;
	void getFDFrRoutes(org.omg.hw.globaldefs.NameAndStringValue_T[][] fdfrNameList, org.omg.hw.HW_vpnManager.FDFrRouteInfoList_THolder routeInfoList) throws org.omg.hw.globaldefs.ProcessingFailureException;
}
